#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --time=00:15:00
#SBATCH --job-name=gatherDataF
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=18
#SBATCH -p bdwall
#SBATCH -A AMREX
#SBATCH -o gather_data_F2003_bebop.o%A
#SBATCH -e gather_data_F2003_bebop.e%A
#SBATCH --mail-type=ALL
#SBATCH --mail-user=joneal@anl.gov
 
######################################################################
#####-----             DO NOT ALTER LINES BELOW             -----#####
######################################################################
rm gatherDataF2003_*_*_*_*_*_*.dat

module purge
module load gcc/7.1.0-4bgguyp
module load mpich/3.2-bsq4vhr
module list

export OMP_NUM_THREADS=1
N_THREADS_PER_TEAM=$((36 / $SLURM_NTASKS_PER_NODE))
N_PROCS=$(($SLURM_NTASKS * $N_THREADS_PER_TEAM))
echo "--------------------------------------------------------------"
echo "Number of nodes   = $SLURM_NNODES"
echo "Number of tasks   = $SLURM_NTASKS"
echo "Tasks per node    = $SLURM_NTASKS_PER_NODE"
echo "Threads per task  = $N_THREADS_PER_TEAM"
echo "Number of CPUs    = $N_PROCS"
echo "--------------------------------------------------------------"
echo

for binary in ./gather_data_F2003_*_*.x; do
    $binary $N_THREADS_PER_TEAM
done

