#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --time=00:30:00
#SBATCH --job-name=gatherData
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=18
#SBATCH -p bdwall
#SBATCH -A AMREX
#SBATCH -o gather_data_cpp_bebop.o%A
#SBATCH -e gather_data_cpp_bebop.e%A
#SBATCH --mail-type=ALL
#SBATCH --mail-user=joneal@anl.gov
 
######################################################################
#####-----             DO NOT ALTER LINES BELOW             -----#####
######################################################################

module purge
module load gcc/7.1.0-4bgguyp
module load mpich/3.2-bsq4vhr
module list

export OMP_NUM_THREADS=1
echo "--------------------------------------------------------------"
echo "Number of nodes   = $SLURM_NNODES"
echo "Number of tasks   = $SLURM_NTASKS"
echo "Tasks per node    = $SLURM_NTASKS_PER_NODE"
echo "Cores per task    = $SLURM_CPUS_PER_TASK"
echo "--------------------------------------------------------------"
echo

folder=gather_data_cpp_bebop_$SLURM_JOB_ID ; mkdir $folder ; cd $folder

date
for binary in ../binaries/gather_data_cpp_*_*.x; do
    $binary $SLURM_CPUS_PER_TASK
done
date

