#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --time=00:01:00
#SBATCH --job-name=threadteam
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=18
#SBATCH -p bdwall
#SBATCH -A AMREX
#SBATCH -o test_threadteam_cpp_bebop.o%A
#SBATCH -e test_threadteam_cpp_bebop.e%A
#SBATCH --mail-type=ALL
#SBATCH --mail-user=joneal@anl.gov
 
######################################################################
#####-----             DO NOT ALTER LINES BELOW             -----#####
######################################################################

export OMP_NUM_THREADS=1
echo "--------------------------------------------------------------"
echo "Number of nodes   = $SLURM_NNODES"
echo "Number of tasks   = $SLURM_NTASKS"
echo "Tasks per node    = $SLURM_NTASKS_PER_NODE"
echo "Cores per task    = $SLURM_CPUS_PER_TASK"
echo "--------------------------------------------------------------"
echo

./binaries/test_threadteam_cpp.x       $SLURM_CPUS_PER_TASK
./binaries/test_threadteam_cpp_debug.x $SLURM_CPUS_PER_TASK

