stages:
  - build
  - test

build-all:
  stage: build
  script:
    - echo "I will build now"
    - whoami
    - pwd
    - ls

test-all:
  stage: test
  script:
    - echo "I will test now"
    - whoami
    - pwd
    - ls

