default:
 tags:
 - public
 - shared_ssh

stages:
  - build
  - test
  - after_success

variables:
 RUNTIME_DEP_PATH: /nfs/gce/projects/Milhoja/deps

test_gnu:
 stage: test
 script:
 - module purge
 - module load gcc/7.5.0-7sxdzdq
 - module load mpich/3.3.2-gnu
 - module load anaconda3/2020.02
 - cd $HOME/$CI_PROJECT_DIR && ./setup.py -t Grid -d 1 -p grid_1d.par -s gce -M Makefile.site.ci && cd build && make -j4 all && make test
 - cd $HOME/$CI_PROJECT_DIR && ./setup.py -t Grid -d 2 -p grid_2d.par -s gce -M Makefile.site.ci && cd build && make -j4 all && make test
 - cd $HOME/$CI_PROJECT_DIR && ./setup.py -t Grid -d 3 -p grid_3d.par -s gce -M Makefile.site.ci && cd build && make -j4 all && make test

test_doxygen:
 stage: test
 script:
 - pushd docs/doxygen && doxygen && popd

