BINARYNAME          = test_runtime_gpu.x

TESTROOTDIR         = $(BASEDIR)/test
TESTBASEDIR         = $(TESTROOTDIR)/Base
RUNTIMEDIR          = $(TESTROOTDIR)/Runtime
TESTDIR             = $(RUNTIMEDIR)/gpu

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(TESTDIR) -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CXXFLAGS_GTEST)
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(TESTDIR) -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CXXFLAGS_GTEST)
CUFLAGS_TEST        = -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CUFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
    $(TESTBASEDIR)/setInitialConditions.cpp \
    $(TESTBASEDIR)/errorEstBlank.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels.cpp \
    $(TESTBASEDIR)/Analysis.cpp \
    $(TESTDIR)/cgkit.DataPacket_gpu_dens_stream.cpp \
    $(TESTDIR)/cgkit.DataPacket_gpu_ener_stream.cpp \
    $(TESTDIR)/cgkit.DataPacket_gpu_dens_ener_stream.cpp \
    $(TESTDIR)/cgkit.DataPacket_gpu_de_1_stream.cpp \
    $(TESTDIR)/testRuntime.cpp \
    $(RUNTIMEDIR)/runRuntimeTests.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedActions_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernelsStrong_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernelsWeak_packet_oacc_summit.cpp

