# Define the desired binary name with BINARYNAME
BINARYNAME          = test_runtime_gpu.x

# Define relevant paths
RUNTIMEDIR          = $(BASEDIR)/test/Runtime
TESTDIR             = $(RUNTIMEDIR)/gpu
TESTBASEDIR         = $(BASEDIR)/test/Base

# Define compiler flags in CXXFLAGS_TEST
CXXFLAGS_TEST_DEBUG = -I$(TESTDIR) -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CXXFLAGS_GTEST)
CXXFLAGS_TEST_PROD  = -I$(TESTDIR) -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CXXFLAGS_GTEST)
CUFLAGS_TEST        = -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CUFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

# Define list of sources in SRCS_TEST
SRCS_TEST = \
    $(SRCDIR)/DataPacket.cpp \
	$(SRCDIR)/MoverUnpacker.cpp \
    $(TESTBASEDIR)/setInitialConditions.cpp \
    $(TESTBASEDIR)/setInitialConditions_tile_cpu.cpp \
    $(TESTBASEDIR)/errorEstBlank.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedActions_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernelsWeak_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernelsStrong_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/Analysis.cpp \
    $(TESTDIR)/DataPacket_gpu_1_stream.cpp \
    $(TESTDIR)/DataPacket_gpu_2_stream.cpp \
    $(RUNTIMEDIR)/testRuntime.cpp \
    $(RUNTIMEDIR)/runRuntimeTests.cpp
