# Define the desired binary name with BINARYNAME
BINARYNAME          = test_runtime_cuda.x

# Define relevant paths
RUNTIMEDIR          = $(BASEDIR)/test/Runtime
TESTDIR             = $(RUNTIMEDIR)/cuda
TESTBASEDIR         = $(BASEDIR)/test/Base

# Define compiler flags in CXXFLAGS_TEST
CXXFLAGS_TEST_DEBUG = -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CXXFLAGS_GTEST) $(OACC_FLAGS) -DUSE_CUDA_BACKEND -DENABLE_OPENACC_OFFLOAD
CXXFLAGS_TEST_PROD  = -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CXXFLAGS_GTEST) $(OACC_FLAGS) -DUSE_CUDA_BACKEND -DENABLE_OPENACC_OFFLOAD
CUFLAGS_TEST        = -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CUFLAGS_GTEST)                -DUSE_CUDA_BACKEND -DENABLE_OPENACC_OFFLOAD
LDFLAGS_TEST        = $(LIB_GTEST) $(OACC_FLAGS)

# Define list of sources in SRCS_TEST
SRCS_TEST = \
    $(SRCDIR)/DataPacket.cpp \
	$(SRCDIR)/MoverUnpacker.cpp \
	$(SRCDIR)/CudaBackend.cpp \
    $(TESTBASEDIR)/setInitialConditions.cpp \
    $(TESTBASEDIR)/setInitialConditions_tile_cpu.cpp \
    $(TESTBASEDIR)/errorEstBlank.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedActions_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernelsWeak_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernelsStrong_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/Analysis.cpp \
    $(RUNTIMEDIR)/testRuntime.cpp \
    $(RUNTIMEDIR)/runRuntimeTests.cpp

CU_SRCS = \
    $(SRCDIR)/CudaGpuEnvironment.cu \
    $(SRCDIR)/CudaDataPacket.cu \
    $(SRCDIR)/CudaStreamManager.cu \
    $(SRCDIR)/CudaMemoryManager.cu

