# Define the desired binary name with BINARYNAME
BINARYNAME    = sedov_cpu_cpp.x

# Define relevant paths
SEDOVDIR      = $(BASEDIR)/simulations/Sedov
TESTDIR       = $(BASEDIR)/simulations/Sedov/cpu

# Define compiler flags in CXXFLAGS_TEST
CXXFLAGS_TEST = -I$(SEDOVDIR) -I$(TESTDIR)
LDFLAGS_TEST  =

# Define list of sources in SRCS_TEST
SRCS_TEST      = \
	$(SEDOVDIR)/Driver_data.cpp \
	$(SEDOVDIR)/errorEstBlank.cpp \
	$(SEDOVDIR)/Eos_idealGammaDensIe.cpp \
	$(SEDOVDIR)/Io.cpp \
	$(SEDOVDIR)/Io_computeIntegralQuantitiesByBlock_tile_cpu.cpp \
	$(SEDOVDIR)/hy_computeFluxesHll.cpp \
	$(SEDOVDIR)/hy_updateSolutionHll.cpp \
	$(SEDOVDIR)/Simulation_setInitialConditions_tile_cpu.cpp \
	$(SEDOVDIR)/sim_setInitialConditions.cpp \
	$(TESTDIR)/Hydro_advanceSolutionHll_tile_cpu.cpp \
	$(TESTDIR)/sedov_cpu.cpp
