BINARYNAME          = sedov_gpu.x

TESTROOTDIR         = $(BASEDIR)/test
SEDOVDIR            = $(TESTROOTDIR)/Sedov
SEDOVGPUDIR         = $(SEDOVDIR)/gpu
TESTDIR             = $(SEDOVGPUDIR)/DataPacket_Hydro_gpu_2

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(SEDOVGPUDIR) -I$(TESTDIR)
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(SEDOVGPUDIR) -I$(TESTDIR)
CUFLAGS_TEST        = -I$(SEDOVDIR)
LDFLAGS_TEST        =

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
	$(SEDOVDIR)/errorEstBlank.cpp \
	$(SEDOVDIR)/ProcessTimer.cpp \
	$(SEDOVDIR)/sim_setInitialConditions.cpp \
	$(SEDOVDIR)/sim_getVariableNames.cpp \
	$(SEDOVDIR)/Simulation_setInitialConditions_tile_cpu.cpp \
	$(SEDOVDIR)/Eos_idealGammaDensIe.cpp \
    $(SEDOVDIR)/hy_computeFluxesHll.cpp \
    $(SEDOVDIR)/hy_updateSolutionHll.cpp \
    $(SEDOVDIR)/Hydro_advanceSolutionHll_tile_cpu.cpp \
	$(SEDOVGPUDIR)/hy_computeSoundSpeedHll_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_X_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_Y_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_Z_oacc_summit.cpp \
	$(TESTDIR)/hy_updateDensityHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateVelxHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateVelyHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateVelzHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateEnergyHll_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeEintHll_oacc_summit.cpp \
	$(SEDOVGPUDIR)/Eos_idealGammaDensIe_oacc_summit.cpp \
	$(SEDOVDIR)/Io.cpp \
	$(SEDOVDIR)/Io_computeIntegralQuantitiesByBlock_tile_cpu.cpp \
	$(SEDOVDIR)/Driver_data.cpp \
	DataPacket_Hydro_gpu_2.cpp \
	$(TESTDIR)/Hydro_advanceSolutionHll_packet_oacc_summit_2.cpp \
	$(TESTDIR)/Driver_executeSimulation.cpp \
	$(SEDOVDIR)/solve_sedov_with_runtime.cpp
