BINARYNAME          = test_runtime_null.x

TESTROOTDIR         = $(BASEDIR)/test
RUNTIMEDIR          = $(TESTROOTDIR)/Runtime
TESTDIR             = $(RUNTIMEDIR)/null

CXXFLAGS_TEST_DEBUG = -I$(TESTDIR) $(CXXFLAGS_GTEST)
CXXFLAGS_TEST_PROD  = -I$(TESTDIR) $(CXXFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

SRCS_TEST = \
    $(TESTDIR)/testRuntimeNull.cpp \
    $(TESTDIR)/runRuntimeTests.cpp

