BINARYNAME          = sedov_gpu.x

TESTROOTDIR         = $(BASEDIR)/test
SEDOVDIR            = $(TESTROOTDIR)/Sedov
SEDOVGPUDIR         = $(SEDOVDIR)/gpu
TESTDIR             = $(SEDOVGPUDIR)/variant3

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(SEDOVGPUDIR) -I$(TESTDIR) -I$(SEDOVDIR)/cpu/code_generation
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(SEDOVGPUDIR) -I$(TESTDIR) -I$(SEDOVDIR)/cpu/code_generation
CUFLAGS_TEST        = -I$(SEDOVDIR)
LDFLAGS_TEST        =

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
	$(SEDOVDIR)/errorEstBlank.cpp \
	$(SEDOVDIR)/ProcessTimer.cpp \
	$(SEDOVDIR)/sim_setInitialConditions.cpp \
	$(SEDOVDIR)/sim_getVariableNames.cpp \
	$(SEDOVDIR)/Simulation_setInitialConditions_tile_cpu.cpp \
	$(SEDOVDIR)/Eos_idealGammaDensIe.cpp \
    $(SEDOVDIR)/hy_computeFluxesHll.cpp \
    $(SEDOVDIR)/hy_updateSolutionHll.cpp \
	$(SEDOVGPUDIR)/hy_computeSoundSpeedHll_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_X_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_Y_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_Z_oacc_summit.cpp \
	$(TESTDIR)/hy_updateSolutionHll_oacc_summit.cpp \
	$(SEDOVGPUDIR)/Eos_idealGammaDensIe_oacc_summit.cpp \
	$(SEDOVDIR)/Io.cpp \
	$(SEDOVDIR)/Io_computeIntegralQuantitiesByBlock_tile_cpu.cpp \
	$(SEDOVDIR)/Driver_data.cpp \
	$(TESTDIR)/DataPacket_Hydro_gpu_3.cpp \
	$(TESTDIR)/Hydro_advanceSolutionHll_packet_oacc_summit_3.cpp \
	$(TESTDIR)/Driver_executeSimulation.cpp \
	$(SEDOVDIR)/solve_sedov_with_runtime.cpp \
	$(SEDOVDIR)/cpu/code_generation/cpu_tf00_$(NDIM)D.cpp
