# Define the desired binary name with BINARYNAME
BINARYNAME    = sedov_gpu_cpp.x

# Define relevant paths
SEDOVDIR   = $(BASEDIR)/simulations/Sedov
TESTDIR    = $(BASEDIR)/simulations/Sedov/gpu

# Define compiler flags in CXXFLAGS_TEST
CXXFLAGS_TEST = -I$(SEDOVDIR) -I$(TESTDIR) -DUSE_CUDA_BACKEND \
                -DENABLE_OPENACC_OFFLOAD
CUFLAGS_TEST = -I$(SEDOVDIR) -I$(TESTDIR) -DUSE_CUDA_BACKEND \
                -DENABLE_OPENACC_OFFLOAD
LDFLAGS_TEST  = -lcudart -L$(CUDADIR)/lib64

# Adjust flags for OpenMP (OACC_FLAGS defined in Makefile.site)
CXXFLAGS_TEST += $(OACC_FLAGS)
LDFLAGS_TEST  += $(OACC_FLAGS)

# Define list of sources in SRCS_TEST
SRCS_TEST      = \
	$(SRCDIR)/DataPacket.cpp \
	$(SRCDIR)/MoverUnpacker.cpp \
	$(SEDOVDIR)/errorEstBlank.cpp \
	$(SEDOVDIR)/sim_setInitialConditions.cpp \
	$(SEDOVDIR)/Simulation_setInitialConditions_tile_cpu.cpp \
    $(SEDOVDIR)/hy_computeFluxesHll.cpp \
    $(SEDOVDIR)/hy_updateSolutionHll.cpp \
	$(TESTDIR)/hy_computeSoundSpeedHll_oacc_summit.cpp \
	$(TESTDIR)/hy_computeFluxesHll_X_oacc_summit.cpp \
	$(TESTDIR)/hy_computeFluxesHll_Y_oacc_summit.cpp \
	$(TESTDIR)/hy_computeFluxesHll_Z_oacc_summit.cpp \
	$(TESTDIR)/hy_scaleSolutionHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateSolutionHll_FlX_oacc_summit.cpp \
	$(TESTDIR)/hy_updateSolutionHll_FlY_oacc_summit.cpp \
	$(TESTDIR)/hy_updateSolutionHll_FlZ_oacc_summit.cpp \
	$(TESTDIR)/hy_rescaleSolutionHll_oacc_summit.cpp \
	$(TESTDIR)/hy_computeEintHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateDensityHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateVelxHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateVelyHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateVelzHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateEnergyHll_oacc_summit.cpp \
	$(TESTDIR)/hy_updateSolutionHll_oacc_summit.cpp \
    $(SEDOVDIR)/Hydro_advanceSolutionHll_tile_cpu.cpp \
	$(TESTDIR)/Hydro_advanceSolutionHll_packet_oacc_summit_1.cpp \
	$(TESTDIR)/Hydro_advanceSolutionHll_packet_oacc_summit_2.cpp \
	$(TESTDIR)/Hydro_advanceSolutionHll_packet_oacc_summit_3.cpp \
	$(SEDOVDIR)/Eos_idealGammaDensIe.cpp \
	$(TESTDIR)/Eos_idealGammaDensIe_oacc_summit.cpp \
	$(TESTDIR)/Eos_idealGammaDensIe_packet_oacc_summit.cpp \
	$(SEDOVDIR)/Io.cpp \
	$(SEDOVDIR)/Io_computeIntegralQuantitiesByBlock_tile_cpu.cpp \
	$(SEDOVDIR)/Driver_data.cpp \
	$(TESTDIR)/sedov_gpu.cpp


CU_SRCS       = \
	$(SRCDIR)/CudaGpuEnvironment.cu \
	$(SRCDIR)/CudaDataPacket.cu \
	$(SRCDIR)/CudaStreamManager.cu \
	$(SRCDIR)/CudaMemoryManager.cu
