BINARYNAME          = sedov_gpu.x

TESTROOTDIR         = $(BASEDIR)/test
SEDOVDIR            = $(TESTROOTDIR)/Sedov
SEDOVGPUDIR         = $(SEDOVDIR)/gpu
SEDOVGPUV3DIR       = $(SEDOVGPUDIR)/variant3
TESTDIR             = $(SEDOVGPUV3DIR)/gpuonly

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(SEDOVGPUDIR) -I$(SEDOVGPUV3DIR) -I$(TESTDIR)
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(SEDOVGPUDIR) -I$(SEDOVGPUV3DIR) -I$(TESTDIR)
CUFLAGS_TEST        = -I$(SEDOVDIR)
LDFLAGS_TEST        =

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
	$(SEDOVDIR)/errorEstBlank.cpp \
	$(SEDOVDIR)/ProcessTimer.cpp \
	$(SEDOVDIR)/sim_setInitialConditions.cpp \
	$(SEDOVDIR)/sim_getVariableNames.cpp \
	$(SEDOVDIR)/Simulation_setInitialConditions_tile_cpu.cpp \
	$(SEDOVDIR)/Eos_idealGammaDensIe.cpp \
    $(SEDOVDIR)/hy_computeFluxesHll.cpp \
    $(SEDOVDIR)/hy_updateSolutionHll.cpp \
    $(SEDOVDIR)/Hydro_advanceSolutionHll_tile_cpu.cpp \
	$(SEDOVGPUDIR)/hy_computeSoundSpeedHll_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_X_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_Y_oacc_summit.cpp \
	$(SEDOVGPUDIR)/hy_computeFluxesHll_Z_oacc_summit.cpp \
	$(SEDOVGPUV3DIR)/hy_updateSolutionHll_oacc_summit.cpp \
	$(SEDOVGPUDIR)/Eos_idealGammaDensIe_oacc_summit.cpp \
	$(SEDOVDIR)/Io.cpp \
	$(SEDOVDIR)/Io_computeIntegralQuantitiesByBlock_tile_cpu.cpp \
	$(SEDOVDIR)/Driver_data.cpp \
	$(SEDOVGPUV3DIR)/DataPacket_Hydro_gpu_3.cpp \
	$(SEDOVGPUV3DIR)/Hydro_advanceSolutionHll_packet_oacc_summit_3.cpp \
	$(TESTDIR)/Driver_executeSimulation_gpuonly.cpp \
	$(SEDOVDIR)/solve_sedov_with_runtime.cpp
