# Define the desired binary name with BINARYNAME
BINARYNAME          = sedov_gpu.x

# Define relevant paths
SEDOVDIR            = $(BASEDIR)/test/Sedov
SEDOVGPUDIR         = $(BASEDIR)/test/Sedov/gpu
SEDOVGPUV3DIR       = $(BASEDIR)/test/Sedov/gpu/variant3
TESTDIR             = $(BASEDIR)/test/Sedov/gpu/variant3/gpuonly

# Define compiler flags in CXXFLAGS_TEST_*
CXXFLAGS_TEST_DEBUG = -I$(SEDOVDIR) -I$(SEDOVGPUDIR) -I$(SEDOVGPUV3DIR) -I$(TESTDIR) $(OACC_FLAGS) -DUSE_CUDA_BACKEND -DENABLE_OPENACC_OFFLOAD
CXXFLAGS_TEST_PROD  = -I$(SEDOVDIR) -I$(SEDOVGPUDIR) -I$(SEDOVGPUV3DIR) -I$(TESTDIR) $(OACC_FLAGS) -DUSE_CUDA_BACKEND -DENABLE_OPENACC_OFFLOAD
CUFLAGS_TEST        = -I$(SEDOVDIR)                                                                -DUSE_CUDA_BACKEND -DENABLE_OPENACC_OFFLOAD
LDFLAGS_TEST        = $(OACC_FLAGS)

# Define list of sources in SRCS_TEST
SRCS_TEST = \
	$(SRCDIR)/DataPacket.cpp \
	$(SRCDIR)/MoverUnpacker.cpp \
	$(SEDOVDIR)/errorEstBlank.cpp \
	$(SEDOVDIR)/ProcessTimer.cpp \
	$(SEDOVDIR)/sim_setInitialConditions.cpp \
	$(SEDOVDIR)/Simulation_setInitialConditions_tile_cpu.cpp \
	$(SEDOVDIR)/Eos_idealGammaDensIe.cpp \
    $(SEDOVDIR)/hy_computeFluxesHll.cpp \
    $(SEDOVDIR)/hy_updateSolutionHll.cpp \
    $(SEDOVDIR)/Hydro_advanceSolutionHll_tile_cpu.cpp \
	$(SEDOVDIR)/Io.cpp \
	$(SEDOVDIR)/Io_computeIntegralQuantitiesByBlock_tile_cpu.cpp \
	$(SEDOVDIR)/Driver_data.cpp \
	$(SEDOVGPUV3DIR)/DataPacket_Hydro_gpu_3.cpp \
	$(SEDOVGPUV3DIR)/Hydro_advanceSolutionHll_packet_oacc_summit_3.cpp \
	$(TESTDIR)/sedov_gpuonly_3.cpp
#	$(SEDOVGPUDIR)/hy_computeSoundSpeedHll_oacc_summit.cpp \
#	$(SEDOVGPUDIR)/hy_computeFluxesHll_X_oacc_summit.cpp \
#	$(SEDOVGPUDIR)/hy_computeFluxesHll_Y_oacc_summit.cpp \
#	$(SEDOVGPUDIR)/hy_computeFluxesHll_Z_oacc_summit.cpp \
#	$(SEDOVGPUV3DIR)/hy_updateSolutionHll_oacc_summit.cpp \
#	$(SEDOVGPUDIR)/Eos_idealGammaDensIe_oacc_summit.cpp \

CU_SRCS = \
	$(SRCDIR)/CudaBackend.cu \
	$(SRCDIR)/CudaGpuEnvironment.cu \
	$(SRCDIR)/CudaStreamManager.cu \
	$(SRCDIR)/CudaMemoryManager.cu
