BINARYNAME          = sedov_cpu.x

TESTROOTDIR         = $(BASEDIR)/test
SEDOVDIR            = $(TESTROOTDIR)/Sedov
TESTDIR             = $(SEDOVDIR)/cpu

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(TESTDIR)
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(TESTDIR)
LDFLAGS_TEST        =

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
	$(SEDOVDIR)/Driver_data.cpp \
	$(SEDOVDIR)/errorEstBlank.cpp \
	$(SEDOVDIR)/ProcessTimer.cpp \
	$(SEDOVDIR)/Eos_idealGammaDensIe.cpp \
	$(SEDOVDIR)/Io.cpp \
	$(SEDOVDIR)/Io_computeIntegralQuantitiesByBlock_tile_cpu.cpp \
	$(SEDOVDIR)/hy_computeFluxesHll.cpp \
	$(SEDOVDIR)/hy_updateSolutionHll.cpp \
	$(SEDOVDIR)/Simulation_setInitialConditions_tile_cpu.cpp \
	$(SEDOVDIR)/sim_setInitialConditions.cpp \
	$(SEDOVDIR)/sim_getVariableNames.cpp \
	$(SEDOVDIR)/Hydro_advanceSolutionHll_tile_cpu.cpp \
	$(TESTDIR)/Driver_executeSimulation.cpp \
	$(SEDOVDIR)/solve_sedov_with_runtime.cpp
