BINARYNAME          = test_grid_multiple.x

TESTGRIDDIR         = $(BASEDIR)/test/Grid
TESTDIR             = $(TESTGRIDDIR)/multiple
TESTBASEDIR         = $(BASEDIR)/test/Base

CXXFLAGS_TEST_DEBUG = -I$(TESTBASEDIR) -I$(TESTGRIDDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST)
CXXFLAGS_TEST_PROD  = -I$(TESTBASEDIR) -I$(TESTGRIDDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

SRCS_TEST = \
    $(TESTDIR)/runGridTest.cpp \
    $(TESTDIR)/gridUnitTest.cpp \
    $(TESTDIR)/errorEstMultiple.cpp \
    $(TESTGRIDDIR)/setInitialInteriorTest.cpp

