# Define the desired binary name with BINARYNAME
BINARYNAME    = test_runtime_cuda.x

# Define relevant paths
TESTDIR       = $(BASEDIR)/test/Runtime
TESTBASEDIR   = $(BASEDIR)/test/Base

PGIDIR        = $(OLCF_PGI_ROOT)/linuxpower/19.9

# Define compiler flags in CXXFLAGS_TEST
CXXFLAGS_TEST_PROD  = -I$(TESTBASEDIR) -I$(TESTDIR) -DUSE_CUDA_BACKEND \
		-DENABLE_OPENACC_OFFLOAD -UNDEBUG
CXXFLAGS_TEST_DEBUG = -I$(TESTBASEDIR) -I$(TESTDIR) -DUSE_CUDA_BACKEND \
		-DENABLE_OPENACC_OFFLOAD -UNDEBUG
CUFLAGS_TEST  = -I$(PGIDIR)/include -I$(TESTBASEDIR) -I$(TESTDIR) \
		-DUSE_CUDA_BACKEND -DENABLE_OPENACC_OFFLOAD -UNDEBUG \
		-D__PGI
LDFLAGS_TEST  = -lcudart -L$(CUDADIR)/lib64 -L$(PGIDIR)/lib

# This test uses Google Test
CXXFLAGS_TEST += $(CXXFLAGS_GTEST)
CUFLAGS_TEST  += $(CXXFLAGS_GTEST)
LDFLAGS_TEST  += $(LIB_GTEST)

# This test uses OACC
CXXFLAGS_TEST += $(OACC_FLAGS)
LDFLAGS_TEST  += $(OACC_FLAGS)

# Define list of sources in SRCS_TEST
SRCS_TEST      = \
    $(SRCDIR)/DataPacket.cpp \
	$(SRCDIR)/MoverUnpacker.cpp \
    $(TESTBASEDIR)/setInitialConditions.cpp \
    $(TESTBASEDIR)/setInitialConditions_tile_cpu.cpp \
    $(TESTBASEDIR)/errorEstBlank.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedActions_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernelsWeak_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernelsStrong_packet_oacc_summit.cpp \
    $(TESTBASEDIR)/Analysis.cpp \
    $(TESTDIR)/testRuntime.cpp \
    $(TESTDIR)/runRuntimeTests.cpp

CU_SRCS       = \
    $(SRCDIR)/CudaGpuEnvironment.cu \
    $(SRCDIR)/CudaDataPacket.cu \
    $(SRCDIR)/CudaStreamManager.cu \
    $(SRCDIR)/CudaMemoryManager.cu
