BINARYNAME          = test_grid_gcfill.x

TESTGRIDDIR         = $(BASEDIR)/test/Grid
TESTDIR             = $(TESTGRIDDIR)/gcfill

CXXFLAGS_TEST_DEBUG = -I$(TESTGRIDDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST)
CXXFLAGS_TEST_PROD  = -I$(TESTGRIDDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

SRCS_TEST = \
    $(TESTDIR)/runGridTest.cpp \
    $(TESTDIR)/gridUnitTest.cpp \
    $(TESTGRIDDIR)/setInitialInteriorTest.cpp \
    $(TESTGRIDDIR)/errorEstMaximal.cpp

