BINARYNAME          = test_grid_gcfill.x

TESTROOTDIR         = $(BASEDIR)/test
TESTBASEDIR         = $(TESTROOTDIR)/Base
TESTGRIDDIR         = $(TESTROOTDIR)/Grid
TESTDIR             = $(TESTGRIDDIR)/gcfill

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(TESTBASEDIR) -I$(TESTGRIDDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST)
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(TESTBASEDIR) -I$(TESTGRIDDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
    $(TESTDIR)/runGridTest.cpp \
    $(TESTDIR)/gridUnitTest.cpp \
    $(TESTGRIDDIR)/setInitialInteriorTest.cpp \
    $(TESTGRIDDIR)/errorEstMaximal.cpp

