BINARYNAME          = test_runtime_cpu.x

TESTROOTDIR         = $(BASEDIR)/test
TESTBASEDIR         = $(TESTROOTDIR)/Base
RUNTIMEDIR          = $(TESTROOTDIR)/Runtime
TESTDIR             = $(RUNTIMEDIR)/cpu

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CXXFLAGS_GTEST)
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(TESTBASEDIR) -I$(RUNTIMEDIR) $(CXXFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
    $(TESTBASEDIR)/setInitialConditions.cpp \
    $(TESTBASEDIR)/setInitialConditions_tile_cpu.cpp \
    $(TESTBASEDIR)/errorEstBlank.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity.cpp \
    $(TESTBASEDIR)/computeLaplacianDensity_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy.cpp \
    $(TESTBASEDIR)/computeLaplacianEnergy_tile_cpu.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels.cpp \
    $(TESTBASEDIR)/computeLaplacianFusedKernels_tile_cpu.cpp \
    $(TESTBASEDIR)/Analysis.cpp \
    $(TESTDIR)/testRuntime.cpp \
    $(RUNTIMEDIR)/runRuntimeTests.cpp

