BINARYNAME          = test_grid_general.x

TESTROOTDIR         = $(BASEDIR)/test
TESTBASEDIR         = $(TESTROOTDIR)/Base
TESTGRIDDIR         = $(TESTROOTDIR)/Grid
TESTDIR             = $(TESTGRIDDIR)/general

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(TESTBASEDIR) -I$(TESTGRIDDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST) -I$(TESTBASEDIR)/code_generation
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(TESTBASEDIR) -I$(TESTGRIDDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST) -I$(TESTBASEDIR)/code_generation
LDFLAGS_TEST        = $(LIB_GTEST)

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
    $(TESTDIR)/runGridTest.cpp \
    $(TESTDIR)/gridUnitTest.cpp \
    $(TESTBASEDIR)/sim_getVariableNames.cpp \
    $(TESTBASEDIR)/setInitialConditions.cpp \
    $(TESTBASEDIR)/setInitialConditions_noRuntime.cpp \
    $(TESTBASEDIR)/code_generation/cpu_tf_ic.cpp \
    $(TESTBASEDIR)/code_generation/Tile_cpu_tf_ic.cpp \
    $(TESTGRIDDIR)/errorEstMaximal.cpp

