#!/bin/bash

#BSUB -P AST136
#BSUB -W 0:10
#BSUB -nnodes 1
#BSUB -alloc_flags smt1
#BSUB -J gatherDataCpp
#BSUB -o gatherDataCpp.%J
#BSUB -e gatherDataCpp.%J
 
######################################################################
#####-----              FULLY SPECIFY TEST RUN              -----#####
######################################################################
# IMPORTANT: Match this to X in smtX BSUB statment above
N_HYPERTHREADS_PER_CORE=1
BINARY=./gather_data_256_32.x

######################################################################
#####-----             DO NOT ALTER LINES BELOW             -----#####
######################################################################
# Resource Set = One MPI process/socket + maximal number of cores per MPI process
# NOTE: We only want one MPI rank in total.  Leave second socket idle.
N_PROC_PER_RS=1
N_GPU_PER_PROC=0
N_CORES_PER_PROC=21
N_RS_PER_SOCKET=1
N_RS_PER_NODE=1

# Fixed hardware information
N_SOCKET_PER_NODE=2
N_GPU_PER_SOCKET=3

# Dynamically determine the number of nodes from LSF env var
# The host output contains the word batch1 and repeats of the hosts names
N_HOST_LINES=$(echo $LSB_HOSTS | tr ' ' '\n' | sort -u | wc -l)
N_NODES=$(($N_HOST_LINES - 1))

# Derived results
N_TOTAL_RS=$(($N_NODES * $N_RS_PER_NODE))
N_GPU_PER_RS=$(($N_GPU_PER_PROC * $N_PROC_PER_RS))
N_CORES_PER_RS=$(($N_CORES_PER_PROC * $N_PROC_PER_RS))
N_THREADS_PER_PROC=$(($N_HYPERTHREADS_PER_CORE * $N_CORES_PER_PROC))

# No need for OpenMP
export OMP_NUM_THREADS=1

echo "---------------------------------------------------------------------"
echo "Number of Nodes               = $N_NODES"
echo "Number of RS Per Node         = $N_RS_PER_NODE"
echo "Number of Resource Sets (RS)  = $N_TOTAL_RS"
echo "Number of Processes per RS    = $N_PROC_PER_RS"
echo "Number of GPU per Process     = $N_GPU_PER_PROC"
echo "Number of Cores per Process   = $N_CORES_PER_PROC"
echo "Number of HW Threads per Core = $N_HYPERTHREADS_PER_CORE"
echo "Number of Threads per Process = $N_THREADS_PER_PROC"
echo "---------------------------------------------------------------------"

folder=/gpfs/alpine/scratch/joneal/ast136/OrchestrationRuntime/gatherDataCpp_$LSB_JOBID
mkdir -p $folder ; cd $folder
cp $LS_SUBCWD/gather_data_*_*.x .

jsrun -n $N_RS_PER_NODE \
      -r $N_RS_PER_NODE \
      -a $N_PROC_PER_RS \
      -c $N_CORES_PER_RS \
      -g $N_GPU_PER_RS \
      -l CPU-CPU -d packed -b packed:1 \
      $BINARY $N_THREADS_PER_PROC

