# Define the desired binary name with BINARYNAME
BINARYNAME          = test_threadteam.x

# Define relevant paths
TESTDIR             = $(BASEDIR)/test/ThreadTeam

# Define compiler flags in CXXFLAGS_TEST_*
# This test uses Google Test
CXXFLAGS_TEST_DEBUG = -I$(TESTDIR) $(CXXFLAGS_GTEST) -DDEBUG_RUNTIME
CXXFLAGS_TEST_PROD  = -I$(TESTDIR) $(CXXFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

# Define list of sources in SRCS_TEST
SRCS_TEST = \
    $(TESTDIR)/estimateTimerResolution.cpp \
    $(TESTDIR)/testThreadRoutines.cpp \
    $(TESTDIR)/testThreadTeam.cpp \
    $(TESTDIR)/runThreadTeamTest.cpp
