BINARYNAME          = test_threadteam.x

TESTROOTDIR         = $(BASEDIR)/test
TESTDIR             = $(TESTROOTDIR)/ThreadTeam

CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST) -DDEBUG_RUNTIME
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(TESTDIR) $(CXXFLAGS_GTEST)
LDFLAGS_TEST        = $(LIB_GTEST)

SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
    $(TESTDIR)/estimateTimerResolution.cpp \
    $(TESTDIR)/testThreadRoutines.cpp \
    $(TESTDIR)/testThreadTeam.cpp \
    $(TESTDIR)/runThreadTeamTest.cpp
