# Define the desired binary name with BINARYNAME
BINARYNAME          = sedov_mpi.x

# Define relevant paths
TESTROOTDIR         = $(BASEDIR)/test
SEDOVDIR            = $(TESTROOTDIR)/Sedov
TESTDIR             = $(TESTROOTDIR)/Sedov/mpi

# Define compiler flags in CXXFLAGS_TEST_*
CXXFLAGS_TEST_DEBUG = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(TESTDIR)
CXXFLAGS_TEST_PROD  = -I$(TESTROOTDIR) -I$(SEDOVDIR) -I$(TESTDIR)
LDFLAGS_TEST        =

# Define list of sources in SRCS_TEST
SRCS_TEST = \
	$(TESTROOTDIR)/RuntimeParameters.cpp \
	$(SEDOVDIR)/Driver_data.cpp \
	$(SEDOVDIR)/ProcessTimer.cpp \
	$(SEDOVDIR)/errorEstBlank.cpp \
	$(SEDOVDIR)/Eos_idealGammaDensIe.cpp \
	$(SEDOVDIR)/Io.cpp \
	$(SEDOVDIR)/hy_computeFluxesHll.cpp \
	$(SEDOVDIR)/hy_updateSolutionHll.cpp \
	$(SEDOVDIR)/Simulation_setInitialConditions_tile_cpu.cpp \
	$(SEDOVDIR)/sim_setInitialConditions.cpp \
	$(SEDOVDIR)/sim_getVariableNames.cpp \
	$(TESTDIR)/Driver_executeSimulation.cpp \
	$(SEDOVDIR)/solve_sedov_without_runtime.cpp
