name: doxygen

on: [push]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/doxygen
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Run doxygen
        run: doxygen

